
[build]
  # Tell Netlify that your build output is inside 'frontend/dist'
  publish = "frontend/dist" 
  # Tell Netlify that your build command runs from the 'frontend' directory
  base = "frontend"
  # ❗ CORRECTED PATH: Relative to the 'frontend' base directory
  functions = "src/functions" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200