# netlify.toml (in the repository root)
[build]
  # Tell Netlify that your build output is inside 'frontend/dist'
  publish = "frontend/dist" 
  # Tell Netlify that your build command runs from the 'frontend' directory
  base = "frontend"
  # Tell Netlify where to find your serverless functions
  functions = "functions"  # This should match the path to your functions folder (e.g., 'functions' or 'frontend/functions')

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200