[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build.environment]
  # Instruct Netlify to skip scanning for the values of these specific keys
  SECRETS_SCAN_OMIT_KEYS = "VITE_EMAILJS_PUBLIC_KEY,VITE_EMAILJS_SERVICE_ID,VITE_EMAILJS_TEMPLATE_ID"